"""The hand-written Alembic baseline must produce the same schema as the ORM models."""

from __future__ import annotations

import asyncio

import pytest
from alembic import command
from alembic.config import Config


async def test_upgrade_head_matches_orm_metadata(
    pg_async_url: str, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setenv("DATABASE_URL", pg_async_url)

    cfg = Config("alembic.ini")
    await asyncio.to_thread(command.upgrade, cfg, "head")
    # Raises AutogenerateDiffsDetected if the models and the migrated schema disagree.
    await asyncio.to_thread(command.check, cfg)
