/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Leads */
        get: operations["list_leads_leads_get"];
        put?: never;
        /** Create Lead */
        post: operations["create_lead_leads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leads/{lead_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lead */
        get: operations["get_lead_leads__lead_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/graphql": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Handle Http Get */
        get: operations["handle_http_get_graphql_get"];
        put?: never;
        /** Handle Http Post */
        post: operations["handle_http_post_graphql_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ContactIn */
        ContactIn: {
            /** Name */
            name: string;
            /** Email */
            email: string;
            /** Company */
            company?: string | null;
            /** Role */
            role?: string | null;
            /** Message */
            message?: string | null;
        };
        /** ContactOut */
        ContactOut: {
            /** Name */
            name: string;
            /** Email */
            email: string;
            /** Company */
            company: string | null;
            /** Role */
            role: string | null;
            /** Message */
            message: string | null;
        };
        /** EnrichmentOut */
        EnrichmentOut: {
            /** Industry */
            industry: string | null;
            /** Company Size Band */
            company_size_band: string | null;
            /** Seniority */
            seniority: string | null;
            /** Intent Signals */
            intent_signals: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LeadCreatedOut */
        LeadCreatedOut: {
            /** Id */
            id: string;
            /** Deduplicated */
            deduplicated: boolean;
        };
        /** LeadIn */
        LeadIn: {
            /** Source */
            source: string;
            contact: components["schemas"]["ContactIn"];
        };
        /** LeadOut */
        LeadOut: {
            /** Id */
            id: string;
            /** Source */
            source: string;
            /** Status */
            status: string;
            /** Failure Reason */
            failure_reason: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            contact: components["schemas"]["ContactOut"];
            enrichment: components["schemas"]["EnrichmentOut"] | null;
            score: components["schemas"]["ScoreOut"] | null;
            reply_draft: components["schemas"]["ReplyDraftOut"] | null;
            sync_state: components["schemas"]["SyncStateOut"] | null;
        };
        /** ReplyDraftOut */
        ReplyDraftOut: {
            /** Subject */
            subject: string;
            /** Body */
            body: string;
        };
        /** ScoreOut */
        ScoreOut: {
            /** Value */
            value: number;
            /** Band */
            band: string;
            /** Rationale */
            rationale: string;
        };
        /** SyncStateOut */
        SyncStateOut: {
            /** Status */
            status: string;
            /** Crm Contact Id */
            crm_contact_id: string | null;
            /** Failure Reason */
            failure_reason: string | null;
            /** Synced At */
            synced_at: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_leads_leads_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_lead_leads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeadIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadCreatedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lead_leads__lead_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    handle_http_get_graphql_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The GraphiQL integrated development environment. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Not found if GraphiQL or query via GET are not enabled. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    handle_http_post_graphql_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
